/**
 * Mock Disclosure Package
 *
 * Simulates Zentity creating a disclosure package for the exchange.
 * Uses mock PII data encrypted to the exchange's public key.
 */

import { type NextRequest, NextResponse } from "next/server";

// Mock PII data (in real flow, this comes from user's verified data)
const MOCK_PII = {
  fullName: "Juan Carlos Perez Martinez",
  dateOfBirth: "1990-05-15",
  nationality: "DOMINICANA",
  documentNumber: "001-1234567-8",
};

// Mock ZK proofs (in real flow, these are generated by the ZK service)
const MOCK_AGE_PROOF = {
  proof: {
    pi_a: ["1234567890", "9876543210", "1"],
    pi_b: [
      ["1111", "2222"],
      ["3333", "4444"],
      ["1", "0"],
    ],
    pi_c: ["5555", "6666", "1"],
    protocol: "groth16",
    curve: "bn128",
  },
  publicSignals: ["1", "18"], // [isOver18, ageThreshold]
};

const MOCK_FACE_MATCH_PROOF = {
  proof: {
    pi_a: ["2345678901", "8765432109", "1"],
    pi_b: [
      ["2222", "3333"],
      ["4444", "5555"],
      ["1", "0"],
    ],
    pi_c: ["6666", "7777", "1"],
    protocol: "groth16",
    curve: "bn128",
  },
  publicSignals: ["1", "6000"], // [isMatch, threshold*10000]
};

const MOCK_DOC_VALIDITY_PROOF = {
  proof: {
    pi_a: ["3456789012", "7654321098", "1"],
    pi_b: [
      ["3333", "4444"],
      ["5555", "6666"],
      ["1", "0"],
    ],
    pi_c: ["7777", "8888", "1"],
    protocol: "groth16",
    curve: "bn128",
  },
  publicSignals: ["1", "20241205"], // [isValid, currentDate]
};

export async function POST(request: NextRequest) {
  try {
    const { rpPublicKey } = await request.json();

    if (!rpPublicKey) {
      return NextResponse.json(
        { error: "rpPublicKey is required" },
        { status: 400 },
      );
    }

    // Parse the public key
    const publicKeyJwk = JSON.parse(rpPublicKey);

    // Import the public key
    const publicKey = await crypto.subtle.importKey(
      "jwk",
      publicKeyJwk,
      { name: "RSA-OAEP", hash: "SHA-256" },
      false,
      ["encrypt"],
    );

    // Generate AES key for hybrid encryption
    const aesKey = await crypto.subtle.generateKey(
      { name: "AES-GCM", length: 256 },
      true,
      ["encrypt", "decrypt"],
    );

    // Encrypt PII with AES
    const iv = crypto.getRandomValues(new Uint8Array(12));
    const piiBytes = new TextEncoder().encode(JSON.stringify(MOCK_PII));
    const encryptedPii = await crypto.subtle.encrypt(
      { name: "AES-GCM", iv },
      aesKey,
      piiBytes,
    );

    // Encrypt AES key with RSA
    const aesKeyRaw = await crypto.subtle.exportKey("raw", aesKey);
    const encryptedAesKey = await crypto.subtle.encrypt(
      { name: "RSA-OAEP" },
      publicKey,
      aesKeyRaw,
    );

    // Create liveness attestation
    const livenessAttestation = {
      verified: true,
      timestamp: new Date().toISOString(),
      signature: `mock-signature-${crypto.randomUUID().slice(0, 8)}`,
    };

    // Build disclosure package
    const disclosurePackage = {
      encryptedPii: {
        iv: Buffer.from(iv).toString("base64"),
        encryptedData: Buffer.from(encryptedPii).toString("base64"),
        encryptedAesKey: Buffer.from(encryptedAesKey).toString("base64"),
      },
      proofs: {
        ageProof: MOCK_AGE_PROOF,
        faceMatchProof: MOCK_FACE_MATCH_PROOF,
        docValidityProof: MOCK_DOC_VALIDITY_PROOF,
      },
      livenessAttestation,
      metadata: {
        issuedAt: new Date().toISOString(),
        expiresAt: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        rpId: "crypto-exchange-demo",
      },
    };

    return NextResponse.json(disclosurePackage);
  } catch (_error) {
    return NextResponse.json(
      { error: "Failed to create disclosure package" },
      { status: 500 },
    );
  }
}
